### PR TITLE
Add to jenkins

### PR DESCRIPTION
**Pull request by ddelnano**
@briancavalier I believe you are the one that started this repo, so if you add the web hooks the jenkins build will be all setup!

When running the linting I got this error.  Looks like eslint is crashing.

screen shot 2016-06-16 at 7 49 19 pm

### CODE REVIEW

**Comment by ddelnano** [comment]
test this please.

**Comment by jbrockett** [comment]
test this please.

**Comment by briancavalier** [comment]
We'll need to update the eslint-config dep, and eslint, babel-eslint, and pin babylon in the same way we had to in check-status-service.

> so if you add the web hooks the jenkins build will be all setup!

Unfortunately, I don't seem to have admin access on this repo either :/

**Comment by briancavalier** [comment]
> We'll need to update the eslint-config dep, and eslint, babel-eslint, and pin babylon

See [this commit](https://github.com/nowait/check-status-service/pull/94/commits/253046d197ea4539ef29b48ade19d71cabb24975) for the changes I had to make to eslintrc, and package.json.

**Comment by ddelnano** [comment]
@briancavalier it passed cause I forgot to add the linting in there, its in the template node package repo but messed it up for some of the jobs I made.

**Comment by jbrockett** [comment]
The webhooks are setup on this repo

**Comment by ddelnano** [comment]
Yea its a linting problem.  Sorry @briancavalier tagged you for the web hook stuff before Jeremy set it up.

**Comment by ddelnano** [comment]
and on fixing the build.

**Comment by ddelnano** [comment]
test this please.

**Comment by ddelnano** [comment]
hmm still having issues...

screen shot 2016-06-17 at 12 09 18 pm

**Comment by briancavalier** [comment]
Good grief ... what is going on with eslint these days:  I'm following the trail here: https://github.com/eslint/eslint/issues/6274.  There may be a workaround.

**Comment by briancavalier** [comment]
test this please.

**Comment by ddelnano** [comment]
test this please.

**Comment by ddelnano** [comment]
test this please.

**Comment by ddelnano** [comment]
rebased on #10

**Comment by ddelnano** [comment]
test this please.

**Pull request closed without merging**
